name: 🌞 Feature
description: "Suggest an idea for this project"
title: "iOS / Android / BE – [featurename] short description"
type: Feature

body:
  - type: textarea
    id: feature-description
    attributes:
      label: "Describe the feature"
      description: "A clear description of what the feature is."
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Dependencies and details about the feature"
      description: "List any related issues, repositories, or external requirements. Link design, behaviour, expected interactions..."
      placeholder: "E.g. Depends on"
    validations:
      required: false

  - type: textarea
    id: estimated-time
    attributes:
      label: "Estimated time"
      description: "How long might it take you?"
      placeholder: "Days"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - High
        - Medium
        - Low
    validations:
      required: false

